#!/usr/bin/env python3
"""Render docs/reference.generated.md from spec.json.

Usage:
  scripts/gen-reference.py           write the file
  scripts/gen-reference.py --check   fail if the committed file is out of date

Every document this repository generates ends in `.generated.md`; see
AGENTS.md. Values live in spec.json and nowhere else -- the hand-written docs
link here instead of restating them.
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO / "spec.json"
OUT = REPO / "docs" / "reference.generated.md"

BANNER = (
    "<!-- GENERATED by scripts/gen-reference.py from spec.json. Do not edit. -->"
)


def render(spec):
    lines = [BANNER, "", "# Reference values", ""]
    lines += [
        "Generated from [`spec.json`](../spec.json). To update, run "
        "`python3 scripts/gen-reference.py`.",
        "",
        "## Constants",
        "",
        "| Key | Value |",
        "|---|---|",
        "| `name` | `%s` |" % spec["name"],
    ]
    for key, value in spec["defaults"].items():
        lines.append("| `defaults.%s` | `%s` |" % (key, value))
    lines += ["", "## Asset sections", ""]
    for category, headings in spec["headings"].items():
        lines += [
            "### %s" % category.capitalize(),
            "",
            "| Section |",
            "|---|",
        ]
        for heading in headings:
            lines.append("| `## %s` |" % heading)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv):
    spec = json.loads(SPEC_PATH.read_text())
    text = render(spec)
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            sys.stderr.write(
                "%s is out of date; run python3 scripts/gen-reference.py\n"
                % OUT.relative_to(REPO)
            )
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print("wrote %s" % OUT.relative_to(REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
