#!/usr/bin/env python3
"""Render the generated documentation from spec.json.

Usage:
  scripts/gen-docs.py           write the files
  scripts/gen-docs.py --check   fail if any committed file is out of date

Every generated document is a whole file under `docs/` named
`*.generated.md` -- the constants and section reference, plus one catalog per
category. Hand-written pages link to them; they never carry generated tables.
Values live in spec.json and nowhere else.
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO / "spec.json"
DOCS = REPO / "docs"
EXCERPT_LEN = 80

BANNER = "<!-- GENERATED by scripts/gen-docs.py from spec.json. Do not edit. -->"


def singular(category):
    return (category[:-1] if category.endswith("s") else category).capitalize()


def assets(category, spec):
    """Yield (label, path) for every asset of a category.

    Catalog indexes are not assets; for a directory asset the entry file is
    the one that carries the sections.
    """
    root = REPO / spec["defaults"]["assets"] / category
    for entry in sorted(root.iterdir()):
        if entry.is_dir():
            yield entry.name + "/", entry / spec["defaults"]["skillEntry"]
        elif entry.name != "README.md":
            yield entry.name, entry


def excerpt(path, heading):
    """The body of the asset's first section, collapsed and cropped."""
    text = path.read_text()
    match = re.search(
        r"^## %s\s*$\n(.*?)(?=^## |\Z)" % re.escape(heading),
        text,
        re.MULTILINE | re.DOTALL,
    )
    body = re.sub(r"\s+", " ", match.group(1)).strip() if match else ""
    if len(body) > EXCERPT_LEN:
        body = body[: EXCERPT_LEN - 1].rsplit(" ", 1)[0] + "…"
    return body


def render_reference(spec):
    lines = [BANNER, "", "# Reference values", ""]
    lines += [
        "Generated from [`spec.json`](../spec.json). To update, run "
        "`python3 scripts/gen-docs.py`.",
        "",
        "## Constants",
        "",
        "| Key | Value |",
        "|---|---|",
        "| `name` | `%s` |" % spec["name"],
    ]
    for key, value in spec["defaults"].items():
        lines.append("| `defaults.%s` | `%s` |" % (key, value))
    lines += ["", "## Asset sections", ""]
    for category, headings in spec["headings"].items():
        lines += [
            "### %s" % category.capitalize(),
            "",
            "| Section |",
            "|---|",
        ]
        for heading in headings:
            lines.append("| `## %s` |" % heading)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_catalog(category, spec):
    first = spec["headings"][category][0]
    lines = [BANNER, "", "# %s" % category.capitalize(), "", "| %s | Excerpt |" % singular(category), "|---|---|"]
    for label, path in assets(category, spec):
        rel = path.relative_to(REPO).as_posix()
        lines.append("| [`%s`](../%s) | %s |" % (label, rel, excerpt(path, first)))
    lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def outputs(spec):
    """Every generated file, as a path relative to the repo root."""
    files = {"docs/reference.generated.md": render_reference(spec)}
    for category in spec["headings"]:
        files["docs/%s.generated.md" % category] = render_catalog(category, spec)
    return files


def main(argv):
    spec = json.loads(SPEC_PATH.read_text())
    files = outputs(spec)
    stale = [
        name
        for name in sorted(files)
        if not (REPO / name).exists() or (REPO / name).read_text() != files[name]
    ]
    stray = sorted(
        p.relative_to(REPO).as_posix()
        for p in DOCS.glob("*.generated.md")
        if p.relative_to(REPO).as_posix() not in files
    )
    if "--check" in argv:
        for name in stale + stray:
            sys.stderr.write(
                "%s is out of date; run python3 scripts/gen-docs.py\n" % name
            )
        return 1 if stale or stray else 0
    for name in stale:
        (REPO / name).parent.mkdir(parents=True, exist_ok=True)
        (REPO / name).write_text(files[name])
        print("wrote %s" % name)
    for name in stray:
        (REPO / name).unlink()
        print("removed %s" % name)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
